dist: xenial
language: python
arch: 
- 'arm64'
- 'amd64'
python:
- '3.7'
install:
- pip install pipenv
- pip install codecov
- pipenv install --dev
script:
- coverage run --source simple_dispatch -m unittest discover
deploy:
  provider: pypi
  user: zprobst
  on:
    tags: true
  password:
    secure: Vf43srGTD0dWtfgCoGnI8hdNt3+arUCkXrYOfkkjU1zghsopS/mvsejdXyHwQ78FetwR6XX8HkPjCcOjRr3qX0ZSFNv8+C28AtcrDvNansc9+Lxo1cGuwoKKt9wN4MjvwzPs4ABICU+gOCvO0Nkm0yVRCUCXSmyFvmv/mlaWIvzeD5Sic1gAPzLccXudyyB4GL28OZCTFRYGhIeNpU3ISWz3B1znk2mHfHIpZvqs1hqlDQB+BjlsFH4aE13aJ1TOxJrtw6omnHmdbDm9j4R8EHH8stL6sBdjUTl0YM8/FHmTJQZ9kwGWAe5dtE7mSJ0+2gyMlp4hxpKAMYMKL3LXbTmK2n4vUYS6bDy9enfMNbpZEn9RsFe7DZaLFEVZa3t0WYMCeXvw1eX2c7Dl5nxJTvbB9wEnh1lfdPOQN3UFs73ZqnUrDijJ3dWTTSD6oAcfjySKan1jvu7l7fCpovx1FpciWTVBHneD3yxRNYqRs+LjFM/y5D+QYWP6fUyxjjFIUG0kndpJ+VDewaG8bVS9QZVFBz0V+Gm0cxXK5125NPMO0SDnrYNiYtUB5L9F8Ksr/ZHFxKqPMAkv0eUFzV/qcCbl5kVMZPXCKeAKlQQz31V6LMcvRUbhx/EllM02zggoGpe8b9/T6wl6Db6axlebhQY+I/BT3VhpkP6yZdU99kQ=
after_success:
- codecov
